package logging.battleLogger;

import java.util.HashSet;
import java.util.Map;
import java.util.PriorityQueue;

import battle.CombatActor;
import battle.CombatTarget;
import battle.ShieldInstance;
import battle.ShipInstance;
import ships.Fleet;

public class DebugBattleLogger implements BattleLogger {
    private int round = 0;

    private DebugBattleLogger() {}

    public static DebugBattleLogger getNewDebugBattleLogger() {
        return new DebugBattleLogger();
    }

    @Override
    public void showFormup(HashSet<Fleet> allFleets,
                           HashSet<ShipInstance> allShips,
                           PriorityQueue<CombatActor> combatActors, 
                           Map<Integer, Fleet> enemiesOfEmpireX,
                           int numParticipatingFighters) {
        System.out.println("Formup: ");
        for (Fleet fleet : allFleets) {
            System.out.println(fleet);
        }

        System.out.println("=== Additional Info ===");
        for (int empireID : enemiesOfEmpireX.keySet()) {
            System.out.println("Enemies of empire " + empireID + ": " + enemiesOfEmpireX.get(empireID).size());
        }
        System.out.println();
        System.out.println("Participating Fighters from carriers: " + numParticipatingFighters);
        System.out.println("Amount of participating Ships: " + allShips.size());
        System.out.println("Amount of active actors: " + combatActors.size());
        System.out.println();
    }

    @Override
    public void shipDestroyed(CombatTarget target) {
        System.out.println("  Target destroyed: " + target);
    }

    @Override
    public void endOfBattle(HashSet<Fleet> allFleets) {
        System.out.println("\nEnd of battle! Ships remaining: ");
        for (Fleet fleet : allFleets) {
            System.out.println(fleet);
        }
    }

    @Override
    public void endOfSingleAttack(ShipInstance attacker) {}

    @Override
    public void beginSingleAttack(final CombatActor attacker, final CombatTarget target, int currentIni) {
        System.out.println("Round " + round + " (ini " + currentIni + "): " + attacker + " goes against " + target);
    }

    @Override
    public void nextRound() {
        round++;
    }

    @Override
    public void shipReacts(CombatTarget target) {
        System.out.println("  " + target + " reacts successfully!");
    }

    @Override
    public void evades(ShipInstance ship, boolean doesEvade, int acc, int evade, int addedAccuracy) {
        if (doesEvade) {
            System.out.println("  " + ship + " evades all damage (" + acc + "<=" + evade + " with bonus of " + addedAccuracy + ")");
        } else {
            System.out.println("  " + ship + " is hit (" + acc + ">" + evade + " with bonus of " + addedAccuracy + ")");
        }
    }

    @Override
    public void armorDeflectsAllDamage(ShipInstance ship, int hitStrength, int glanceThreshold) {
        System.out.println("  Armor of " + ship + " deflects all Damage! (" + hitStrength + "<=" + glanceThreshold + ")");
    }

    @Override
    public void takesHullDamage(ShipInstance ship, double damage, HullDamageLevel damageLevel, int hitStrength, int threshold) {
        System.out.println("  " + ship + " takes " + (int) damage + " points of " + damageLevel + " damage  (" + hitStrength + ">" + threshold + ")");
    }

    @Override
    public void explodes(ShipInstance ship, double explodeChance, int hitStrength, int critThreshold, int containment) {
        System.out.println("  " + ship + " explodes!!! Chance was " + String.format("%1$.2f", explodeChance * 100) + "% (" + hitStrength + ">" + critThreshold + ", " + containment + ")");
    }

    @Override
    public void shieldBreaks(ShieldInstance shield, int breakDuration) {
        System.out.println("  Shield of " + shield.getOwner() + " breaks for " + breakDuration + " ticks!");
    }

    @Override
    public void takesShieldDamage(ShieldInstance shield, double amount) {
        System.out.println("  Shield of " + shield.getOwner() + " deflects " + (int) amount + " points of damage");
    }

    @Override
    public void regeneratesShield(ShieldInstance shield, double regeneration, double shieldNow) {
        System.out.println("  Shields of " + shield.getOwner() + " regenerated by " + String.format("%1$.1f", regeneration) + " to " + String.format("%1$.1f", shieldNow));
    }

    @Override
    public void preysOnPreferredTargetType(CombatActor ship) {
        System.out.println("  Preys on preferred Target type!");
    }

    @Override
    public void hasResupplied(ShipInstance ship, ShipInstance mothership) {
        System.out.println("  " + ship + ": Resupplied at " + mothership);
    }

	@Override
	public void noActiveParticipantsInCombat() {
		System.out.println("No participants take an active part in this battle.");
	}

    @Override
    public void shipLosesTicks(ShipInstance shipInstance, int lostTicks, int chanceInPermill) {
        System.out.println("  " + shipInstance + " loses " + lostTicks + " ticks due to effect (chance was " + String.format("%1$.2f", ((double) chanceInPermill) / 10) + "%)");
    }

    @Override
    public void shipArmorDegrades(ShipInstance shipInstance, int amount) {
        System.out.println("  " + shipInstance + " loses " + amount + " on all armor thresholds due to effect");
    }
}
